name: Packer Build - AMI Creation on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name:  env file
      run: |
        touch .env
          
        echo NODE_PACKER="packer" >> .env
        echo "cat .env"
        cat .env

    - name: Zip Job Boards
      run: zip -r job-boards.zip ../job-boards


    - name: Set up Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip
        unzip packer_1.8.3_linux_amd64.zip
        chmod +x packer
        sudo mv packer /usr/local/bin/
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
        unzip packer_1.7.2_linux_amd64.zip
        chmod +x packer
        mv packer /usr/local/bin
      shell: bash

    - name: Run packer init
      run: packer init aws.debian.pkr.hcl
    
    - name: Run `packer Build`
      id: packer_build
      run: |
        echo "Running packer build"
        packer build aws.debian.pkr.hcl